In [1]:
pip install opencv-python==4.5.3.56

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 7.6 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


In [2]:
import cv2 ### importing module

In [4]:
ImgData=['/content/drive/MyDrive/Heros','/content/drive/MyDrive/Heroines']

In [3]:
import os  ##  need to install to  see path dir

In [6]:
import os

ImgData = ['/content/drive/MyDrive/Heros','/content/drive/MyDrive/Heroines']

for dir_path in ImgData:  # Iterate over each directory path in the list
    for img in os.listdir(dir_path):  # Use os.listdir() on each individual path
        print(img)

images.jpeg
msid-100582542,width-960,height-1280,resizemode-6.cms
images (1).jpeg
HD-wallpaper-akshay-kumar-bollywood-indian-actor-movie-stars.jpg
Yash to Ram Charan These are the 11 highest-paid South Indian actors.webp
ALLU-ARJUN.webp
images (2).jpeg
images.jpeg
Kriti_Sanon.htm
Kriti_Sanon_at_Adipurush_pre_release_event_(2)_(cropped).jpg
Nayanthara.webp
desktop-wallpaper-disha-patani-bollywood-actress.jpg
10-138.avif
images (1).jpeg


In [9]:
### step 2 : resize all in uniform size
import cv2
from os import listdir
# Update the path to the image directory
ImgData = ['/content/drive/MyDrive/Heros','/content/drive/MyDrive/Heroines']   ### sandeep  patil drive folder images
for dir_path in ImgData: # Iterate over each directory path
    for img in listdir(dir_path): # Use os.listdir() on each individual path
        img_path = os.path.join(dir_path, img) # Construct full path
        img = cv2.imread(img_path) # Read image using the full path
        if img is not None: # Check if image loaded successfully
            Img = cv2.resize(img,(10,10))
            print(f"Resized image: {img}") # Print confirmation
        else:
            print(f"Failed to load image: {img_path}") # Print error message

Resized image: [[[ 49 102  69]
  [ 49 102  69]
  [ 51 101  71]
  ...
  [110 149 123]
  [106 145 119]
  [101 141 116]]

 [[ 49  99  67]
  [ 49  99  67]
  [ 49  99  69]
  ...
  [109 148 122]
  [106 145 120]
  [102 141 116]]

 [[ 48  97  65]
  [ 48  97  65]
  [ 48  96  67]
  ...
  [109 145 121]
  [104 142 120]
  [101 139 117]]

 ...

 [[179 147 148]
  [185 154 155]
  [181 150 151]
  ...
  [179 147 148]
  [180 149 148]
  [181 149 150]]

 [[178 147 148]
  [185 154 155]
  [181 150 151]
  ...
  [159 128 129]
  [157 126 127]
  [156 125 126]]

 [[177 146 147]
  [185 154 155]
  [181 150 151]
  ...
  [144 113 114]
  [139 108 109]
  [133 105 105]]]
Resized image: [[[ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]
  ...
  [103 100 103]
  [103 100 103]
  [103 100 103]]

 [[ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]
  ...
  [103 100 103]
  [103 100 103]
  [103 100 103]]

 [[ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]
  ...
  [103 100 103]
  [103 100 103]
  [103 100 103]]

 ...

 [[103 123 170]
  [103

In [11]:
### step 2 : resize all in uniform size
import cv2
from os import listdir

# Update the path to the image directory
ImgData = ['/content/drive/MyDrive/Heros','/content/drive/MyDrive/Heroines']   ### sandeep  patil drive folder images

for dir_path in ImgData: # Iterate over each directory path
    for img in listdir(dir_path): # Use os.listdir() on each individual path
        img_path = os.path.join(dir_path, img) # Construct full path to the image
        img = cv2.imread(img_path) # Read image using the full path
        if img is not None: # Check if image loaded successfully
            Img = cv2.resize(img,(10,10))
            print(f"Resized image: {img}") # Print confirmation
        else:
            print(f"Failed to load image: {img_path}") # Print error message

Resized image: [[[ 49 102  69]
  [ 49 102  69]
  [ 51 101  71]
  ...
  [110 149 123]
  [106 145 119]
  [101 141 116]]

 [[ 49  99  67]
  [ 49  99  67]
  [ 49  99  69]
  ...
  [109 148 122]
  [106 145 120]
  [102 141 116]]

 [[ 48  97  65]
  [ 48  97  65]
  [ 48  96  67]
  ...
  [109 145 121]
  [104 142 120]
  [101 139 117]]

 ...

 [[179 147 148]
  [185 154 155]
  [181 150 151]
  ...
  [179 147 148]
  [180 149 148]
  [181 149 150]]

 [[178 147 148]
  [185 154 155]
  [181 150 151]
  ...
  [159 128 129]
  [157 126 127]
  [156 125 126]]

 [[177 146 147]
  [185 154 155]
  [181 150 151]
  ...
  [144 113 114]
  [139 108 109]
  [133 105 105]]]
Resized image: [[[ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]
  ...
  [103 100 103]
  [103 100 103]
  [103 100 103]]

 [[ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]
  ...
  [103 100 103]
  [103 100 103]
  [103 100 103]]

 [[ 98  98  98]
  [ 98  98  98]
  [ 98  98  98]
  ...
  [103 100 103]
  [103 100 103]
  [103 100 103]]

 ...

 [[103 123 170]
  [103

In [13]:
## step 3: Converting into grey scale
for dir_path in ImgData:  # Iterate over each directory path
    for img_name in listdir(dir_path):  # List files in each directory
        img_path = os.path.join(dir_path, img_name)  # Full path to image
        img = cv2.imread(img_path)
        if img is not None:
            Img = cv2.resize(img, (10, 10))
            img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert to grayscale
            print(img_gray)  # Print the grayscale image
        else:
            print(f"Failed to load image: {img_path}")

[[ 86  86  86 ... 137 133 129]
 [ 84  84  84 ... 136 133 129]
 [ 82  82  82 ... 134 131 128]
 ...
 [151 158 154 ... 151 152 153]
 [151 158 154 ... 132 130 129]
 [150 158 154 ... 117 112 108]]
[[ 98  98  98 ... 101 101 101]
 [ 98  98  98 ... 101 101 101]
 [ 98  98  98 ... 101 101 101]
 ...
 [135 135 135 ... 136 136 136]
 [136 136 136 ... 136 136 136]
 [136 136 136 ... 136 136 136]]
[[252 213 245 ... 236 201 253]
 [206 117 128 ... 110 107 210]
 [234 117 126 ... 109 109 229]
 ...
 [242 212 211 ... 193 205 244]
 [242 213 212 ... 196 202 237]
 [254 240 239 ... 243 236 251]]
[[ 7  7  7 ...  7  7  7]
 [ 7  7  7 ...  8  8  8]
 [ 7  7  7 ...  8  8  8]
 ...
 [52 49 47 ... 47 55 71]
 [57 53 48 ... 50 53 66]
 [58 54 49 ... 52 52 61]]
[[ 54  47  36 ...  30  28  26]
 [ 53  48  41 ...  30  28  26]
 [ 51  50  48 ...  29  27  24]
 ...
 [133 133 133 ... 134 127 122]
 [133 133 133 ... 142 135 129]
 [132 132 132 ... 141 134 129]]
[[ 89  89  89 ...  95  95  95]
 [ 90  90  90 ...  95  95  95]
 [ 90  90  90 

In [15]:
import cv2
from os import listdir
import numpy as np

## step 4 : converting to array
ImgData = ['/content/drive/MyDrive/Heros','/content/drive/MyDrive/Heroines']   ### sandeep  patil drive folder images

for dir_path in ImgData: # Iterate over each directory path
    for img_name in listdir(dir_path): # Use os.listdir() on each individual path
        img_path = os.path.join(dir_path, img_name) # Construct full path to the image
        img = cv2.imread(img_path) # Read image using the full path
        if img is not None: # Check if image loaded successfully
            Img = cv2.resize(img,(10,10))
            #print(img)  ## image printed in Matrix array form
            img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  ### converting in grey scale all  images
            #img = cv2.COLOR_BGR2GRAY  ### converting in grey scale all  images
            #print(img)
            data = np.array(img)
            print(data)
        else:
            print(f"Failed to load image: {img_path}") # Print error message

[[ 86  86  86 ... 137 133 129]
 [ 84  84  84 ... 136 133 129]
 [ 82  82  82 ... 134 131 128]
 ...
 [151 158 154 ... 151 152 153]
 [151 158 154 ... 132 130 129]
 [150 158 154 ... 117 112 108]]
[[ 98  98  98 ... 101 101 101]
 [ 98  98  98 ... 101 101 101]
 [ 98  98  98 ... 101 101 101]
 ...
 [135 135 135 ... 136 136 136]
 [136 136 136 ... 136 136 136]
 [136 136 136 ... 136 136 136]]
[[252 213 245 ... 236 201 253]
 [206 117 128 ... 110 107 210]
 [234 117 126 ... 109 109 229]
 ...
 [242 212 211 ... 193 205 244]
 [242 213 212 ... 196 202 237]
 [254 240 239 ... 243 236 251]]
[[ 7  7  7 ...  7  7  7]
 [ 7  7  7 ...  8  8  8]
 [ 7  7  7 ...  8  8  8]
 ...
 [52 49 47 ... 47 55 71]
 [57 53 48 ... 50 53 66]
 [58 54 49 ... 52 52 61]]
[[ 54  47  36 ...  30  28  26]
 [ 53  48  41 ...  30  28  26]
 [ 51  50  48 ...  29  27  24]
 ...
 [133 133 133 ... 134 127 122]
 [133 133 133 ... 142 135 129]
 [132 132 132 ... 141 134 129]]
[[ 89  89  89 ...  95  95  95]
 [ 90  90  90 ...  95  95  95]
 [ 90  90  90 

In [17]:
## step 4 : converting to array
import numpy as np
import cv2
from os import listdir

## step 3: Converting into grey scale
for dir_path in ImgData:  # Iterate over directory paths in ImgData
    for img_name in listdir(dir_path):  # List files in each directory
        img_path = os.path.join(dir_path, img_name)  # Full path to image
        img = cv2.imread(img_path)
        if img is not None:
            Img = cv2.resize(img,(10,10))
            #print(img)  ## image printed in Matrix array form
            img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  ### converting in grey scale all  images
            #img = cv2.COLOR_BGR2GRAY  ### converting in grey scale all  images
            #print(img)
            #data = np.array(img)
            # print(data)
            data = np.array(img).flatten()  ## converted in 2d and becomes flatten
            print(data)
        else:
            print(f"Failed to load image: {img_path}")

[ 86  86  86 ... 117 112 108]
[ 98  98  98 ... 136 136 136]
[252 213 245 ... 243 236 251]
[ 7  7  7 ... 52 52 61]
[ 54  47  36 ... 141 134 129]
[ 89  89  89 ... 115 115 115]
[187 187 187 ... 141 140 139]
[117 107  98 ...  48  57  84]
Failed to load image: /content/drive/MyDrive/Heroines/Kriti_Sanon.htm
[133 132 134 ... 141 143 148]
[181 181 181 ...  99  98  98]
[12 12 12 ...  0  0  0]
Failed to load image: /content/drive/MyDrive/Heroines/10-138.avif
[ 79  81  85 ... 230 228 228]


In [19]:
## step 4 : converting to array
import numpy as np
import pandas as pd
import cv2
from os import listdir

## step 3: Converting into grey scale
mydata = [] ## creating empty list for to store all image data  in one place
for dir_path in ImgData: # Iterate over directory paths in ImgData
    for img_name in listdir(dir_path): # Use os.listdir() on each individual path
        img_path = os.path.join(dir_path, img_name) # Construct full path to the image
        img = cv2.imread(img_path) # Read image using the full path
        if img is not None: # Check if image loaded successfully
            Img = cv2.resize(img,(10,10))
            #print(img)  ## image printed in Matrix array form
            img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  ### converting in grey scale all  images
            #img = cv2.COLOR_BGR2GRAY  ### converting in grey scale all  images
            #print(img)
            data = np.array(img)
            # print(data)
            data = np.array(img).flatten()  ## converted in 2d and becomes flatten
            print(data)
            mydata.append(data)  ### adding in empty list created
        else:
            print(f"Failed to load image: {img_path}") # Print error message

[ 86  86  86 ... 117 112 108]
[ 98  98  98 ... 136 136 136]
[252 213 245 ... 243 236 251]
[ 7  7  7 ... 52 52 61]
[ 54  47  36 ... 141 134 129]
[ 89  89  89 ... 115 115 115]
[187 187 187 ... 141 140 139]
[117 107  98 ...  48  57  84]
Failed to load image: /content/drive/MyDrive/Heroines/Kriti_Sanon.htm
[133 132 134 ... 141 143 148]
[181 181 181 ...  99  98  98]
[12 12 12 ...  0  0  0]
Failed to load image: /content/drive/MyDrive/Heroines/10-138.avif
[ 79  81  85 ... 230 228 228]


In [21]:
## step 5 : making 2d and converting in csv file now by pandas
import numpy as np
import pandas as pd
import cv2
from os import listdir

## step 3: Converting into grey scale
mydata = [] ## creating empty list for to store all image data  in one place
for dir_path in ImgData: # Iterate over directory paths in ImgData
    for img_name in listdir(dir_path): # Use os.listdir() on each individual path
        img_path = os.path.join(dir_path, img_name) # Construct full path to the image
        img = cv2.imread(img_path) # Read image using the full path
        if img is not None: # Check if image loaded successfully
            Img = cv2.resize(img,(10,10))
            #print(img)  ## image printed in Matrix array form
            img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  ### converting in grey scale all  images
            #img = cv2.COLOR_BGR2GRAY  ### converting in grey scale all  images
            #print(img)
            data = np.array(img)
            # print(data)
            data = np.array(img).flatten()  ## converted in 2d and becomes flatten
            print(data)
            mydata.append(data)  ### adding in empty list created
        else:
            print(f"Failed to load image: {img_path}") # Print error message
df = pd.DataFrame(mydata)
df.to_csv('mydata.csv',index=False) ## saving file in

[ 86  86  86 ... 117 112 108]
[ 98  98  98 ... 136 136 136]
[252 213 245 ... 243 236 251]
[ 7  7  7 ... 52 52 61]
[ 54  47  36 ... 141 134 129]
[ 89  89  89 ... 115 115 115]
[187 187 187 ... 141 140 139]
[117 107  98 ...  48  57  84]
Failed to load image: /content/drive/MyDrive/Heroines/Kriti_Sanon.htm
[133 132 134 ... 141 143 148]
[181 181 181 ...  99  98  98]
[12 12 12 ...  0  0  0]
Failed to load image: /content/drive/MyDrive/Heroines/10-138.avif
[ 79  81  85 ... 230 228 228]


In [24]:
mydata = []
thelabels = []
# Define the paths to your image directories
imagedata = '/content/drive/MyDrive/Heros'
imagedata1 = '/content/drive/MyDrive/Heroines'
igcat = [imagedata, imagedata1]

for cat in igcat:
  for img in os.listdir(cat):
    img_path = os.path.join(cat, img)
    img = cv2.imread(img_path)
    if img is not None: # Check if image loaded successfully
        img = cv2.resize(img, (1200, 1800))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        data = np.array(img).flatten()
        print(img_path)
        print(data)
        mydata.append(data)  # Append to 'mydata' instead of 'thedata'
        thelabels.append(cat.index)
    else:
        print(f"Failed to load image: {img_path}") # Print error message if image loading fails

/content/drive/MyDrive/Heros/images.jpeg
[ 86  86  86 ... 108 108 108]
/content/drive/MyDrive/Heros/msid-100582542,width-960,height-1280,resizemode-6.cms
[ 98  98  98 ... 136 136 136]
/content/drive/MyDrive/Heros/images (1).jpeg
[252 252 246 ... 250 251 251]
/content/drive/MyDrive/Heros/HD-wallpaper-akshay-kumar-bollywood-indian-actor-movie-stars.jpg
[ 7  7  7 ... 51 56 61]
/content/drive/MyDrive/Heros/Yash to Ram Charan These are the 11 highest-paid South Indian actors.webp
[ 53  43  32 ... 144 136 129]
/content/drive/MyDrive/Heros/ALLU-ARJUN.webp
[ 89  89  89 ... 115 115 115]
/content/drive/MyDrive/Heroines/images (2).jpeg
[187 187 187 ... 139 139 139]
/content/drive/MyDrive/Heroines/images.jpeg
[117 117 117 ...  84  84  84]
Failed to load image: /content/drive/MyDrive/Heroines/Kriti_Sanon.htm
/content/drive/MyDrive/Heroines/Kriti_Sanon_at_Adipurush_pre_release_event_(2)_(cropped).jpg
[133 132 132 ... 142 145 148]
/content/drive/MyDrive/Heroines/Nayanthara.webp
[181 181 181 ...  98  

In [25]:
df = pd.DataFrame(mydata,thelabels)

df.to_csv('CNN_otwo.csv',index=False)

#df = pd.read_csv('CNN_otwo.csv')

#df.head()